./push-swap
echo -e "Does it display nothing?\n"
./push-swap "2 1 3 6 5 8"
echo -e "Does it display a valid solution and less than 9 instructions?\n"
./push-swap "0 1 2 3 4 5"
echo -e "Does it display nothing?\n"
./push-swap "0 one 2 3"
echo -e "Does it display Error?\n"
./push-swap "1 2 2 3"
echo -e "Does it display Error?\n"
./push-swap "1 2 3 4 5"
echo -e "Does it display a valid solution and less than 12 instructions?\n"
./push-swap "5 4 3 2 1"
echo -e "Does it still displays a valid solution and less than 12 instructions?\n"
./checker
echo -e "Does it display nothing?\n"
./checker "0 one 2 3"
echo -e "Does it display Error?\n"
echo -e "sa\npb\nrrr\n" | ./checker "0 9 1 8 2 7 3 6 4 5"
echo -e "Does it display KO?\n"
echo -e "pb\nra\npb\nra\nsa\nra\npa\npa\n" | ./checker "0 9 1 8 2"
echo -e "Does it display OK?\n"
ARG="4 67 3 87 23"; ./push-swap "$ARG" | ./checker "$ARG"
echo -e "Does it display OK?\n"
