echo -e "Q1:"
./push-swap
echo -e "Does it display nothing?"
echo -e "\nQ2:"
./push-swap "2 1 3 6 5 8"
echo -e "Does it display a valid solution and less than 9 instructions?"
echo -e "\nQ3:"
./push-swap "0 1 2 3 4 5"
echo -e "Does it display nothing?"
echo -e "\nQ4:"
./push-swap "0 one 2 3"
echo -e "Does it display Error?"
echo -e "\nQ5:"
./push-swap "1 2 2 3"
echo -e "Does it display Error?"
echo -e "\nQ6:"
./push-swap "3 6 8 4 1"
echo -e "Does it display a valid solution and less than 12 instructions?"
echo -e "\nQ7:"
./push-swap "6 7 8 2 4"
echo -e "Does it still displays a valid solution and less than 12 instructions?"
echo -e "\nQ8:"
./checker
echo -e "Does it display nothing?"
echo -e "\nQ9:"
./checker "0 one 2 3"
echo -e "Does it display Error?"
echo -e "\nQ10:"
echo -e "sa\npb\nrrr\n" | ./checker "0 9 1 8 2 7 3 6 4 5"
echo -e "Does it display KO?"
echo -e "\nQ11:"
echo -e "pb\nra\npb\nra\nsa\nra\npa\npa\n" | ./checker "0 9 1 8 2"
echo -e "Does it display OK?"
echo -e "\nQ12:"
ARG="4 67 3 87 23"; ./push-swap "$ARG" | ./checker "$ARG"
echo -e "Does it display OK?"
rm push-swap checker
